name: Upload Python Package


on:
  release:
    types: [ published ]


permissions:
  contents: read


jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - name: Build distribution
        run: |
          python -m pip install -U pip
          python -m pip install -U build
          python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1